/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StartRaket;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author erika
 */
public class AdminTaBortAlien extends javax.swing.JFrame {
    InfDB idb;

    /**
     * Creates new form AdminTaBortAlien
     */
    public AdminTaBortAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        MetoderFyllaCB.laggTillAlien(cbAlien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        cbAlien = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblText.setText("Vilken Alien vill du ta bort?");

        cbAlien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj en Alien" }));

        btnTaBort.setText("Ta Bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaBort)
                    .addComponent(cbAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblText)
                .addGap(30, 30, 30)
                .addComponent(cbAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnTaBort)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        if(Validering.rattIndexComboBox(cbAlien))
      
        try{
        String namn =  (String) cbAlien.getSelectedItem();
        String idPaAlien = "SELECT Alien_ID from Alien where namn = '" + namn +"'";
        String id = idb.fetchSingle(idPaAlien);

        
        String taBortAlien = "Delete from Alien where Alien_ID = " + id;
        String taBortBoglo = "Delete from boglodite where Alien_ID = " + id;
        String taBortSquid = "Delete from squid where Alien_ID = " + id;
        String taBortWorm  = "Delete from worm where Alien_ID = " + id;

        idb.delete(taBortBoglo);
        idb.delete(taBortSquid);
        idb.delete(taBortWorm);
        idb.delete(taBortAlien);

        JOptionPane.showMessageDialog(null, "Den valda alien är bortagen ur systemet");
        dispose();
        }
        catch(InfException e)
        {
        JOptionPane.showMessageDialog(null, "Något blev fel");
        System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnTaBortActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> cbAlien;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
