/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StartRaket;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author majahawia
 */
public class AdminAndraAgentInfo extends javax.swing.JFrame {
private InfDB idb;
    /**
     * Creates new form AdminAndraAgentInfo
     */
    public AdminAndraAgentInfo(InfDB idb) {
        initComponents();
        this.idb=idb;
        MetoderFyllaCB.laggTillAgent(cbAgent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbAgent = new javax.swing.JComboBox<>();
        btnAndra = new javax.swing.JButton();
        cbInfo = new javax.swing.JComboBox<>();
        txtNyInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ändra Agentinformation!");

        cbAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agent" }));

        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        cbInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj vilken info du vill ändra. ", "Namn", "Telefon", "Anställningsdatum", "Lösenord", "Område" }));
        cbInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInfoActionPerformed(evt);
            }
        });

        txtNyInfo.setColumns(8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnAndra)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnAndra)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
    if(Validering.rattIndexComboBox(cbAgent) && Validering.rattIndexComboBox(cbInfo) && Validering.textFaltHarVarde(txtNyInfo))
 try {
     
   String agentNamn= (String) cbAgent.getSelectedItem();
   String query = "Select Agent_ID from agent where Namn= '" + agentNamn + "'";
   String id = idb.fetchSingle(query);


   if(cbInfo.getSelectedItem().toString().equals("Namn")){
   String Namn= txtNyInfo.getText();
   String uppdateraNamn = "update agent set namn='" + Namn + "' where Agent_ID =" + id;
   idb.update(uppdateraNamn);
   }

   else if(cbInfo.getSelectedItem().toString().equals("Telefon")){
   String Telefon = txtNyInfo.getText();
   String uppdateraTelefon = "update agent set Telefon='" + Telefon + "' where Agent_ID =" + id;
   idb.update(uppdateraTelefon);
   } 
  
   else if(cbInfo.getSelectedItem().toString().equals("Lösenord")){
   String Lösenord = txtNyInfo.getText();
   String uppdateraLösen = "update agent set Lösenord='" + Lösenord + "' where Agent_ID =" + id;
   idb.update(uppdateraLösen);
   }   
   
   else if(cbInfo.getSelectedItem().toString().equals("Område")){
   String Område = txtNyInfo.getText();
   int Omrades_ID=1;
     if (txtNyInfo.equals("Svealand")) {
                Omrades_ID = 1;
            } else if (txtNyInfo.equals("Götaland")) {
                Omrades_ID = 2;
            } else if (txtNyInfo.equals("Norrland")) {
                Omrades_ID = 4;
            } 
   String uppdateraOmråde = "update agent set område="+ Omrades_ID + "' where Agent_ID =" + id;
   idb.update(uppdateraOmråde);
   }   


      JOptionPane.showMessageDialog(null, "Infon har ändrats!");
      }
  

        catch(InfException e)
        {
        JOptionPane.showMessageDialog(null, "Något gick fel");
        System.out.println(e.getMessage());

    }
    }//GEN-LAST:event_btnAndraActionPerformed

    private void cbInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JComboBox<String> cbAgent;
    private javax.swing.JComboBox<String> cbInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNyInfo;
    // End of variables declaration//GEN-END:variables
}
