/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StartRaket;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author erika
 */
public class AdminTaBortAgent extends javax.swing.JFrame {
    private InfDB idb;

    /**
     * Creates new form AdminTaBortAgent
     */
    public AdminTaBortAgent(InfDB idb) {
        initComponents();
        this.idb = idb;
        MetoderFyllaCB.laggTillAgent(cbAgentAttTaBort);
        MetoderFyllaCB.laggTillAgent(cbNyAgent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        lblOBS = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        cbAgentAttTaBort = new javax.swing.JComboBox<>();
        btnTillbaka = new javax.swing.JButton();
        lblAgentTaBort = new javax.swing.JLabel();
        cbNyAgent = new javax.swing.JComboBox<>();
        lblNyAgent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblText.setText("Vilken agent vill du ta bort?");

        lblOBS.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblOBS.setText("OBS: Är du säker? Det är ett jävla meck att lägga till en ny agent ");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        cbAgentAttTaBort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj en agent" }));
        cbAgentAttTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgentAttTaBortActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblAgentTaBort.setText("Agent att ta bort");

        cbNyAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj en agent" }));

        lblNyAgent.setText("Agent att ersätta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOBS)
                    .addComponent(lblText)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentTaBort)
                            .addComponent(lblNyAgent))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbAgentAttTaBort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTaBort)
                            .addComponent(cbNyAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOBS)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAgentAttTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgentTaBort))
                        .addGap(18, 18, 18)
                        .addComponent(cbNyAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNyAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnTaBort)
                .addGap(2, 2, 2)
                .addComponent(btnTillbaka)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAgentAttTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgentAttTaBortActionPerformed
 
    }//GEN-LAST:event_cbAgentAttTaBortActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
    if (Validering.rattIndexComboBox(cbAgentAttTaBort) && Validering.rattIndexComboBox(cbNyAgent))
    try {

            String namnPaAgent = cbAgentAttTaBort.getSelectedItem().toString();
            String idPaAgent = "Select Agent_ID from agent where Namn = '" + namnPaAgent+"'";
            String agent1 = idb.fetchSingle(idPaAgent);

            
            String namnNyAgent = cbNyAgent.getSelectedItem().toString();
            String idNyAgent = "Select Agent_ID FROM agent where Namn = '" + namnNyAgent+"'";
            String agent2 = idb.fetchSingle(idNyAgent);

            String uppdateraAlien = "Update alien set Ansvarig_Agent = " + agent2 + " where ansvarig_Agent = " + agent1;
         
            String taBortOmradesChef = "DELETE FROM omradeschef where Agent_ID = " + agent1;
            
            String taBortFordon = "Delete from innehar_fordon where Agent_ID = " + agent1;
          
            String taBortUtrustning = "Delete from innehar_utrustning where Agent_ID = " + agent1;
            
            String taBortKontorsChef = "Delete FROM kontorschef where Agent_ID = " + agent1;
            
            String taBortFaltAgent = "Delete from faltagent where Agent_ID = " + agent1;

            String taBortAgent = "Delete from agent where Agent_ID = " + agent1;
            

            idb.update(uppdateraAlien);
            idb.delete(taBortOmradesChef);
            idb.delete(taBortFordon);
            idb.delete(taBortUtrustning);
            idb.delete(taBortKontorsChef);
            idb.delete(taBortFaltAgent);
            idb.delete(taBortAgent);



            JOptionPane.showMessageDialog(null, "Agenten är borttagen ur systemet");
            this.setVisible(false);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Det strular");
            System.out.println(e.getMessage());

        }

        
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbAgentAttTaBort;
    private javax.swing.JComboBox<String> cbNyAgent;
    private javax.swing.JLabel lblAgentTaBort;
    private javax.swing.JLabel lblNyAgent;
    private javax.swing.JLabel lblOBS;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
