/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StartRaket;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author majahawia
 */
public class AdminAndraAgentInfo extends javax.swing.JFrame {
private InfDB idb;
    /**
     * Creates new form AdminAndraAgentInfo
     */
    public AdminAndraAgentInfo(InfDB idb) {
        initComponents();
        this.idb=idb;
        MetoderFyllaCB.laggTillAgent(cbAgent);
        lblDatum.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbAgent = new javax.swing.JComboBox<>();
        btnAndra = new javax.swing.JButton();
        cbInfo = new javax.swing.JComboBox<>();
        txtNyInfo = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ändra Agentinformation!");

        cbAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agent" }));

        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        cbInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj vilken info du vill ändra. ", "Namn", "Telefon", "Anställningsdatum", "Lösenord", "Område" }));
        cbInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInfoActionPerformed(evt);
            }
        });

        txtNyInfo.setColumns(8);

        lblDatum.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblDatum.setText("\"\"");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblDatum)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnAndra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(btnTillbaka)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatum))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndra)
                    .addComponent(btnTillbaka))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Denna metod ändrar agentinfo 
    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
    if(Validering.rattIndexComboBox(cbAgent) && Validering.rattIndexComboBox(cbInfo) && Validering.textFaltHarVarde(txtNyInfo))
 try {
     
   String agentNamn= (String) cbAgent.getSelectedItem();
   String query = "Select Agent_ID from agent where Namn= '" + agentNamn + "'";
   String id = idb.fetchSingle(query);


   if(cbInfo.getSelectedItem().toString().equals("Namn")){
   String Namn= txtNyInfo.getText();
   String uppdateraNamn = "update agent set namn='" + Namn + "' where Agent_ID =" + id;
   idb.update(uppdateraNamn);
   }

   else if(cbInfo.getSelectedItem().toString().equals("Telefon")){
   String Telefon = txtNyInfo.getText();
   String uppdateraTelefon = "update agent set Telefon='" + Telefon + "' where Agent_ID =" + id;
   idb.update(uppdateraTelefon);
   } 
  
   else if(cbInfo.getSelectedItem().toString().equals("Lösenord")){
   String Lösenord = txtNyInfo.getText();
   String uppdateraLösen = "update agent set Lösenord='" + Lösenord + "' where Agent_ID =" + id;
   idb.update(uppdateraLösen);
   }   
   
        else if (cbInfo.getSelectedItem().toString().equals("Område")) {
            
            String område = txtNyInfo.getText();
            int Omrades_ID = 1;
            if (område.equals("Svealand")) {
                Omrades_ID = 1;
            }

            if (område.equals("Götaland")) {
                Omrades_ID = 2;
            }

            if (område.equals("Norrland")) {
                Omrades_ID = 4;
            }
            
          

            String uppdateraOmråde = "update agent set omrade=" + Omrades_ID + " where Agent_ID =" + id;
            idb.update(uppdateraOmråde);
        }
        else if(cbInfo.getSelectedItem().toString().equals("Anställningsdatum") && Validering.textArDatum(txtNyInfo))
        {     
         String datum = txtNyInfo.getText();
         String uppdateraDatum = "update agent set anstallningsdatum ='" + datum + "' where Agent_ID =" + id;
         idb.update(uppdateraDatum);
         } 


        JOptionPane.showMessageDialog(null, "Infon har ändrats!");
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Något gick fel");
        System.out.println(e.getMessage());

    }
    }//GEN-LAST:event_btnAndraActionPerformed
// metod som visar text beroende på vilket alternativ i comboboxen som valts
    private void cbInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInfoActionPerformed
        lblDatum.setVisible(true);
        if(cbInfo.getSelectedItem().toString().equals("Anställningsdatum"))
        {lblDatum.setText("Ange det nya datumet, YYYY-MM-DD");}
     
        else if(cbInfo.getSelectedItem().toString().equals("Namn"))
        {lblDatum.setText("Skriv in det nya namnet");}
       
        else if(cbInfo.getSelectedItem().toString().equals("Lösenord"))
        {lblDatum.setText("Skriv in det nya Lösenordet");}
       
        else if(cbInfo.getSelectedItem().toString().equals("Område"))
        {lblDatum.setText("Välj mellan Svealand/Götaland/Norrland");}
       
        else if(cbInfo.getSelectedItem().toString().equals("Telefon"))
        {lblDatum.setText("Skriv in det nya telefonnumret");}
    }//GEN-LAST:event_cbInfoActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminHanteraAgent(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbAgent;
    private javax.swing.JComboBox<String> cbInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JTextField txtNyInfo;
    // End of variables declaration//GEN-END:variables
}
