/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StartRaket;

import oru.inf.InfDB;

/**
 *
 * @author erika
 */
public class AgentSokaAlltAlien extends javax.swing.JFrame {
    private InfDB idb;

    /**
     * Creates new form AgentSokaAlltAlien
     */
    public AgentSokaAlltAlien(InfDB idb) {
        initComponents();
        this.idb=idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeInfo = new javax.swing.JButton();
        btnRegPeriod = new javax.swing.JButton();
        btnOmråde = new javax.swing.JButton();
        btnRas = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSeInfo.setText("Info om specifik Alien");
        btnSeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeInfoActionPerformed(evt);
            }
        });

        btnRegPeriod.setText("Se aliens registreringsperiod ");
        btnRegPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegPeriodActionPerformed(evt);
            }
        });

        btnOmråde.setText("Se Aliens registrerade på en viss plats");
        btnOmråde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmrådeActionPerformed(evt);
            }
        });

        btnRas.setText("Se alien av en viss ras");
        btnRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRasActionPerformed(evt);
            }
        });

        lblText.setText("Vad vill du veta?");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeInfo)
                    .addComponent(lblText)
                    .addComponent(btnRas)
                    .addComponent(btnOmråde)
                    .addComponent(btnRegPeriod))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblText)
                .addGap(29, 29, 29)
                .addComponent(btnSeInfo)
                .addGap(18, 18, 18)
                .addComponent(btnRegPeriod)
                .addGap(22, 22, 22)
                .addComponent(btnOmråde)
                .addGap(18, 18, 18)
                .addComponent(btnRas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTillbaka)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Denna klass skickar användaren vidare till den knapp den trycker på
    private void btnSeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeInfoActionPerformed
        new AgentSokAlien(idb).setVisible(true);
    }//GEN-LAST:event_btnSeInfoActionPerformed

    private void btnOmrådeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmrådeActionPerformed
        new AlienPaPlats(idb).setVisible(true);
    }//GEN-LAST:event_btnOmrådeActionPerformed

    private void btnRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRasActionPerformed
        new AlienAvRas(idb).setVisible(true);
    }//GEN-LAST:event_btnRasActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AgentHanteraAlien(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnRegPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegPeriodActionPerformed
        new AlienRegPeriod(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegPeriodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOmråde;
    private javax.swing.JButton btnRas;
    private javax.swing.JButton btnRegPeriod;
    private javax.swing.JButton btnSeInfo;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
