/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StartRaket;

import oru.inf.InfDB;

/**
 *
 * @author erika
 */
public class InloggadAlien extends javax.swing.JFrame {
    private InfDB idb;
    private String alienNamn;
    private int alienID;

    /**
     * Creates new form InloggadAlien
     */
    public InloggadAlien(InfDB idb, String alienNamn, int alienID) {
        initComponents();
        this.idb = idb;
        this.alienNamn = alienNamn;
        this.alienID = alienID;
        lblVälkommen.setText("Välkommen " + alienNamn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVälkommen = new javax.swing.JLabel();
        btnOmrådesChef = new javax.swing.JButton();
        btnNyttLosen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVälkommen.setText("Välkommen Alien");

        btnOmrådesChef.setText("Områdeschef");
        btnOmrådesChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmrådesChefActionPerformed(evt);
            }
        });

        btnNyttLosen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNyttLosen.setText("Ändra lösenord");
        btnNyttLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyttLosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblVälkommen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnOmrådesChef)
                        .addGap(36, 36, 36)
                        .addComponent(btnNyttLosen)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblVälkommen)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOmrådesChef, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnNyttLosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNyttLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttLosenActionPerformed
        new AndraLosenAlien(idb, alienNamn, alienID).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNyttLosenActionPerformed

    private void btnOmrådesChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmrådesChefActionPerformed
        new OmradeschefInfoForAlien(idb, alienNamn, alienID).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOmrådesChefActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNyttLosen;
    private javax.swing.JButton btnOmrådesChef;
    private javax.swing.JLabel lblVälkommen;
    // End of variables declaration//GEN-END:variables
}
