/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StartRaket;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author erika
 */
public class OmradeschefInfoForAlien extends javax.swing.JFrame {
    private InfDB idb;
    private String alienNamn;
    private int alienID;

    /**
     * Creates new form OmradeschefInfoForAlien
     */
    public OmradeschefInfoForAlien(InfDB idb, String alienNamn, int alienID) {
        initComponents();
        this.idb = idb;
        this.alienNamn = alienNamn;
        this.alienID = alienID;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        lblSeChef = new javax.swing.JLabel();
        lblTelNr = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblText.setText("Information om din områdeschef");

        lblSeChef.setText("Namn");

        lblTelNr.setText("Telefonnummer");

        btnInfo.setText("Hämta info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblText)
                        .addComponent(lblTelNr)
                        .addComponent(lblSeChef))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInfo)
                        .addGap(91, 91, 91)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblText)
                .addGap(40, 40, 40)
                .addComponent(lblSeChef)
                .addGap(26, 26, 26)
                .addComponent(lblTelNr)
                .addGap(33, 33, 33)
                .addComponent(btnInfo)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
  
    }//GEN-LAST:event_btnInfoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel lblSeChef;
    private javax.swing.JLabel lblTelNr;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
